const CH={
  low:[
    'Breathe deep, reset your focus','Nice and easy, let the legs recover','Good rhythm, stay relaxed',
    'Shake it out, you earned this rest','Controlled breathing, controlled power','Easy strokes, conserve energy',
    'Relax the grip, loosen the shoulders','Feel the recovery, sprint is coming',
    'This is your vacation \u2013 enjoy it','Gentle paddle, gentle thoughts','Recharge those legs',
    'Float it out, nice and light','Active recovery is still recovery','Lower that heart rate',
    'Save the energy, you will need it','Slow it down, you are doing great','Arms only if you want',
    'Think happy thoughts, sprint soon','Catch your breath, you beast','Your muscles say thank you',
    'Recovery is where the magic happens','Lighter than a feather on the water','Just vibing right now',
    'Cruise control engaged','Even machines need to idle sometimes','Light strokes, heavy results later',
    'The calm before the storm','Channel your inner sloth (briefly)','Pretend you are rowing through honey',
    'Easy does it, champ','Let gravity do the work','This is the dessert of the workout',
    'Soft hands, quiet mind','Enjoy the silence between sprints','Your heart rate approves of this',
    'Legs on standby, brain on vacation','Rowing in screensaver mode','This is your spa moment',
    'Breathe like you mean it','Coast into the next one','Low gear, high chill',
    'The erg is purring, not roaring','Reset the system','Reloading power cells',
    'Take it easy, take it all','Soak in the calm','You will miss this in about 20 seconds',
    'Glide mode: activated','The only easy part \u2013 savour it','Zero urgency, maximum recovery',
    'Paddle like a gondolier on holiday','Your legs are on airplane mode','This is the eye of the storm',
    'Rest hard so you can go hard','Permission to coast: granted','Your nervous system needed this',
    'Floating on clouds of recovery','The erg is giving you a hug right now','Minimal effort, maximum chill',
    'Power nap for your muscles','Think of a beach \u2013 you are rowing to it gently','Your hamstrings are sending a thank-you card',
    'Rowing at the speed of relaxation','This is the intermission of your epic movie','Low and slow wins the show',
    'Your blood lactate is politely excusing itself','Recovery mode: professional grade','Like rowing through a meadow',
    'Channel the energy of a lazy Sunday','The erg is barely noticing you right now','Whisper strokes only',
    'Your heart rate is getting back to civilian levels','Think of this as rowing in a library','Coasting like a bike downhill',
    'Your quads are throwing a small celebration','Minimum viable effort achieved','Even Formula 1 cars have pit stops',
    'Therapeutic rowing in session','This is the palate cleanser of fitness','Rowing in economy mode',
    'Your mitochondria are catching their breath','Soft rowing, hard results','The Netflix and chill of erging',
    'Recovery: the secret weapon nobody talks about','Keep it moving, keep it mellow',
    'Your future sprint self is being assembled right now','Rowing as if the erg is sleeping','Zen mode: unlocked',
    'The gentlest row you ever did row','Your muscles are filing a thank-you report','The opposite of what is about to happen',
    'Silent rowing, deadly sprinting','Energy conservation protocol active','Like rowing on a calm lake at dawn',
    'The erg does not even know you are there','Your body is doing background maintenance','Stealth rowing engaged',
    'Rest is just horizontal ambition','Storing kinetic energy for later carnage','The quiet part of being extraordinary'
  ],
  moderate:[
    'Building momentum now','Smooth and steady, great form','Feel the power building',
    'Strong strokes, keep it flowing','This is your rhythm, own it','Drive with the legs, connect the chain',
    'Getting stronger every session','Solid pace, sprint is next',
    'You make this look easy','That form though \u2013 chef kiss','Lock in the chain sequence',
    'Like a well-oiled machine','Feel that flywheel spin','Connected and powerful',
    'Your 5K pace called \u2013 it is jealous','Smooth is fast, fast is smooth',
    'Right in the groove','Tempo game is strong','Every stroke is an investment',
    'The engine is humming','This is your bread and butter','Control the slide, own the drive',
    'Textbook rowing right here','Building the foundation of fitness','You are rowing, not fighting the erg',
    'This pace could win elections \u2013 very steady','Efficient power transfer',
    'Keep that drag factor honest','Legs-back-arms like a pro','Rhythm and power in harmony',
    'Moderate effort, maximum gains','Your coach would be proud',
    'Controlled aggression','The sweet spot between easy and hard','Dialled in and dangerous',
    'This is where technique lives','Feel the boat speed (metaphorically)','Purposeful strokes',
    'Not too hot, not too cold \u2013 just right','Stroke by stroke, you are winning',
    'The rhythm section of your workout','Patient power','Hold the line, hold the pace',
    'You could have a conversation right now (but do not)','Cruise altitude reached',
    'Every metre counts','Building horsepower','This is sustainable greatness',
    'Your split time is looking clean','Calm hands, strong legs',
    'You have found the sweet spot','This is what competence looks like','Mechanical efficiency at its best',
    'Your split time would make a clock jealous','Flowing like water through a pipe','The erg is singing your song',
    'Measured power, measured brilliance','You row like you have done this before','Strong and steady, the golden combo',
    'Your chain is telling a beautiful story','This effort is building something special','The seat is sliding, the watts are climbing',
    'Disciplined and devastating','You could teach a class on this form','Locked in like a GPS signal',
    'Your power curve is a work of art','Every catch is crisp, every drive is clean','Rowing poetry in motion',
    'That pace is sustainable AND impressive','The rhythm of a champion in training','Composure under effort, rare and impressive',
    'Your stroke rate is a metronome','This is the engine being built','Fluid power, zero wasted motion',
    'The kind of effort that compounds over time','Looking effortless (we both know it is not)',
    'Your form is holding up beautifully','The flywheel respects consistent effort','Middle gears, maximum progress',
    'This is where the transformation happens','Smooth acceleration, smooth deceleration','Your body is a rowing algorithm',
    'Reliable power output detected','The pace that pays dividends','Technique over brute force, always',
    'Your muscles are synchronised and happy','This effort level has a PhD in fitness','Rowing like a metronome with muscles',
    'Clean catches, powerful finishes','The drive phase is textbook','You are in the zone and the zone is good',
    'Steady power, steady progress','Your handle speed is chef-kiss consistent','The kind of rowing that makes coaches smile',
    'Grace under moderate pressure','Building something bigger than today','Your watts are politely but firmly climbing',
    'Rowing with intention and precision','This is the middle gear of greatness','Sustainable excellence in action'
  ],
  high:[
    'SEND IT!','Everything you have!','Legs, back, arms \u2013 EXPLODE!','Maximum power!','Push through!',
    'This is why you came!','Full send, no holding back!','GO GO GO!','Drive those legs!','Peak power NOW!',
    'BE THE ERG!','Leave nothing in the tank!','Your erg fears you!','POWER POWER POWER!',
    'Sprint like WiFi just came back!','Ten seconds of FURY!','Give it EVERYTHING!',
    'You are UNSTOPPABLE!','Like your life depends on it!','Channel your inner viking!',
    'ATTACK the handle!','Maximum wattage!','The monitor cannot handle you!',
    'Unleash the KRAKEN!','This is your moment!','Sprint first, breathe later!',
    'Row like you stole the boat!','TURBO MODE ACTIVATED!','Every watt counts!',
    'The erg owes you rent!','You are a rowing MACHINE!','Light up that screen!',
    'Absolute CARNAGE on that handle!','Row angry (but with good form)!','BEAST MODE!',
    'You vs. the erg \u2013 you WIN!','Ten seconds of pure chaos!','Make the flywheel SCREAM!',
    'Row like pizza is at the finish!',
    'FASTER FASTER FASTER!','Channel lightning!','The watts do not lie \u2013 smash them!',
    'Your ancestors are watching!','Ten seconds, zero excuses!','Become ungovernable!',
    'Row like the gym is closing!','This is YOUR ten seconds!','VIOLENT acceleration!',
    'The erg did NOT see this coming!','Eject the soul, keep the body rowing!',
    'Sprint like someone unplugged the TV!','Rip that handle!','Break the sound barrier!',
    'Who needs oxygen anyway!','You are pure energy right now!','ATOMIC sprint!',
    'Row first, exist later!','This is not a drill!',
    'THE FINISH LINE IS NOW!','Pedal to the metal, erg edition!','You are a FORCE OF NATURE!',
    'Row like thunder!','MAXIMUM OVERDRIVE!','Your watts just went supersonic!',
    'This sprint is PERSONAL!','Pull like the erg insulted your mother!','OBLITERATE that split!',
    'You are basically a human rocket!','FULL THROTTLE!','The erg regrets being assembled!',
    'Row with the fury of a thousand suns!','TEN SECONDS OF ABSOLUTE MAYHEM!','Your legs do not know the word quit!',
    'DETONATE on the drive!','The monitor is having a panic attack!','You are REWRITING physics!',
    'NUCLEAR launch sequence!','Sprint like rent is due!','Raw, unfiltered POWER!',
    'The handle has never moved this fast!','You are operating at illegal watts!','RAMPAGE on the rails!',
    'This is controlled DEMOLITION!','Your legs are two pistons of DOOM!','IGNITION, we have liftoff!',
    'The flywheel is TERRIFIED!','Row like you found extra gears!','Pure adrenaline, pure power!',
    'THE ERG IS SUBMITTING!','Legs of steel, will of fire!','You are rowing angry and it is BEAUTIFUL!',
    'MAXIMUM EFFORT!','The screen cannot keep up with you!','Sprint like the ghost of Redgrave is watching!',
    'UNLEASH!','Your watts are in the danger zone!','Row like you are late for your own victory!',
    'EXPLOSIVE finish!','The entire gym can hear that flywheel!','You are a one-person STORM!',
    'DEMOLISH that pace!','Sprint like coffee just kicked in!','DANGER: extreme wattage detected!',
    'Your erg needs therapy after this!','Row like there is no tomorrow!','CATASTROPHIC power output!',
    'You are making the erg question its existence!','LAUNCH!','Sprint like your playlist just dropped the beat!',
    'The chain is HUMMING!','You are rowing on ROCKET FUEL!','Ten seconds of glorious VIOLENCE!',
    'THE WATTS DO NOT LIE!','Pull harder than a Monday!','SCORCHED ERG policy!',
    'This is YOUR moment of GLORY!'
  ],
  rest:[
    'Great block, take a breather','Well done, hydrate if you need to','You crushed that one',
    'Let your heart rate come down','Reset and prepare for the next block','Strong work, keep it up',
    'Shake it out, walk it off if you need','That block is DONE, well played','Sip some water, champion',
    'Stretch those forearms','Your lungs will forgive you eventually','Another block conquered',
    'Rest is part of the training','Deep belly breaths','You are tougher than you think',
    'Roll those shoulders back','Stand up and shake it out','That was impressive, not gonna lie',
    'Recovery drink? Fancy. Water? Also great.','Mentally prepare for the next one',
    'You are earning every bit of this rest','One down, glory ahead','Enjoy this \u2013 you earned it',
    'Plot your revenge on the next block',
    'Towel off, you are literally dripping excellence','That block owed you money and you collected',
    'Breathe in confidence, breathe out doubt','Your resting face says champion',
    'The erg is more tired than you are','Recharging superpowers','Two minutes of being a legend on break',
    'Grab some water, you beautiful athlete','The hard part was the block, this is the reward',
    'Your heart rate will return to normal (eventually)','Stand, stretch, be proud',
    'Next block does not stand a chance','You are doing what most people only talk about',
    'Proof that you are tougher than you thought',
    'That was brutal and beautiful','Your erg is catching its breath too','Three words: you did that',
    'Towel time, champion','Deep breaths, deeper pride','You just survived something special',
    'The block is defeated, the rower remains','Rest harder than you rowed (okay maybe not)',
    'Your cardiovascular system is writing a memoir','Take a bow, preferably while hydrating',
    'The erg is licking its wounds','That effort deserves a standing ovation',
    'Walk around if you need to, you earned the mileage','Your lungs called, they want a raise',
    'Congratulations, you are still alive and rowing','That block was a masterpiece of suffering',
    'Your sweat is just liquid pride','Pause, breathe, and appreciate your insanity',
    'The next block will be jealous of that one','Your body is doing rapid repairs right now',
    'If rest were a sport, you would also excel at it','Shaking out legs: the fourth Olympic lift',
    'Your muscles are having a team meeting','Cooling system activated, turbo mode pending',
    'That was textbook block execution','Take this time to question why you love this',
    'The erg is pretending nothing happened','Your fitness level just went up a notch',
    'Hydrate or diedrate, as they say','That block had no idea what hit it',
    'Standing rest burns more than sitting, just saying','You have earned every molecule of oxygen',
    'The next block is warming up nervously','Your recovery is almost as impressive as your work',
    'Wipe down, gear up','You are writing your own success story, one block at a time',
    'The scoreboard is updating in your favour','One step closer to complete erg domination'
  ],
  warmup:[
    'Warming up the engine','Get the blood flowing','Long smooth strokes','Find your rhythm',
    'Gradually build the pace','Loosen up, prepare to work',
    'Wake up those muscles','Easy strokes to start','Hello erg, my old friend',
    'Let the body remember what rowing is','No rush, just smooth movements',
    'Get those joints moving','Incremental power, no heroics yet',
    'First strokes are always the hardest','The erg missed you, probably',
    'Start slow to finish strong','Oil the machine (you are the machine)',
    'Engage the core, relax the mind','Your warm-up is someone else\u2019s workout',
    'Building heat, building focus',
    'Roll those shoulders, wake the back','Let the legs find their rhythm',
    'Easy power, easy breathing','The session has not started yet \u2013 enjoy this',
    'Your body is waking up and saying hello','Slow strokes, big ambitions',
    'Prime the engine, check the systems','Like stretching before a nap, but harder',
    'Mentally rehearse being awesome','This is foreplay for fitness',
    'The erg awaits your greatness','Gentle acceleration, no rush at all','Your joints are negotiating their terms',
    'Pre-flight checks: looking good','Low resistance, high expectations','The warm-up is just the trailer',
    'Your muscles are logging on','Establishing connection with the erg','Every warm-up stroke is an investment',
    'The flywheel is waking up too','Preparing for something beautiful','Lazy strokes with serious intentions',
    'Your back is saying good morning','This is the appetiser','Building momentum from nothing',
    'Your hamstrings are slowly coming online','System boot: 50% complete','The erg is calibrating to your awesomeness',
    'One stroke at a time, no pressure','Your lungs are expanding for business','Think of this as the opening credits',
    'The handle is getting to know you again','Quiet confidence, building gradually','First gear is perfectly fine right now',
    'Your body is loading the firmware update','A journey of a thousand metres starts with one stroke','Easing into excellence',
    'The warm-up is non-negotiable and you know it','Your nervous system is syncing with the erg','Slowly waking the beast within'
  ],
  cooldown:[
    'Great session, bring it down slowly','You did it, easy strokes now','Let the heart rate settle',
    'Proud of you for showing up','Another session in the bank','Cool down, you have earned it',
    'You showed up and delivered','Champion\u2019s cool-down','Smooth it out, wind it down',
    'Your future self thanks you','Post-workout glow activated','That was a proper session',
    'The hard part is over','Easy paddle to the finish','You are officially a better rower now',
    'High-five yourself (mentally)','Recovery starts now','Enjoy the endorphins',
    'The erg respects you now','One more session closer to your goals',
    'Ice bath optional, pride mandatory','Float it home, hero',
    'You just did something most people will not','Victory lap on the erg','Savour it, you earned every second',
    'Your muscles are writing thank-you notes','The best part of the workout: knowing it is done',
    'Gently return to being a normal person','That was elite behaviour',
    'Cool down the body, warm up the pride','Tomorrow you will be stronger because of today',
    'Landing sequence initiated','You are the main character today',
    'Permission to feel smug: granted','Slow strokes, fast recovery','You survived and thrived',
    'Ease it down like a landing plane','Your body is already rebuilding','The workout is complete, the legend grows',
    'Easy rowing to the sunset','Your endorphins are having a party','Deceleration of a champion',
    'The finish line is behind you now','Winding down with pride intact','Your heart is returning to base camp',
    'That was harder than it looked and you still did it','Gentle strokes, giant accomplishment','The cooldown is the bow on top',
    'You can breathe normally again (soon)','The monitor would tip its hat if it could','Rowing into the calm after the storm',
    'Your muscles are singing lullabies','Another session logged, another level reached','The session bows to you',
    'Take your time, the erg is not going anywhere','Your training log just got heavier','Graceful exit from the pain cave',
    'Winding down the engine, one stroke at a time','You finished what you started','The afterglow of effort',
    'Easy rows, happy joints','Returning to earth after a workout in orbit','Your future races just got easier',
    'That was time well spent','The cool-down: where champions reflect','Rowing off into the credits'
  ],
  steady:[
    'Find your rhythm, hold it steady','Long smooth strokes','Focus on consistent split time',
    'Breathe evenly, stay relaxed','Building aerobic base','Good steady effort',
    'Every stroke counts','Keep the pace, keep the form','Settle in, enjoy the row',
    'Sustainable power, smooth chain','This is where endurance is built','Zen and the art of rowing',
    'Consistent is the new fast','Metronomic precision','Steady wins the race',
    'Your cardiovascular system says thanks','The engine room is purring',
    'This is productive suffering at its finest','Marathon pace, marathon mindset',
    'Think of this as a moving meditation','You could do this all day (almost)',
    'Smooth water, smooth strokes','Building the aerobic monster within',
    'Same split, same effort, same legend','The tortoise always wins',
    'Embrace the monotony, it is working','Row like a clock \u2013 tick, tick, tick',
    'Volume is the secret sauce','Your VO2max is quietly improving',
    'Just you, the erg, and consistency',
    'Steady as a heartbeat','This is what discipline looks like','You are banking fitness',
    'Hold the split, hold the dream','Quiet power, loud results','Tick tock, erg clock',
    'Zone 2 is where champions are built','You are sculpting endurance',
    'If rowing were music, this is the bassline','Comfort zone? No. Growth zone? Yes.',
    'The longer you hold, the stronger you get','Patience is a superpower',
    'This is how you build an engine','Steady hands, steady heart, steady legend',
    'The miles are adding up','Nothing fancy, just effective',
    'The rhythm is the reward','Consistency is your superpower today','Your aerobic engine is purring',
    'Think of this as investing in your future self','Same stroke, different minute, same legend','The erg appreciates your dedication',
    'Endurance is not loud, but it is powerful','This is the foundation of everything',
    'Your stroke rate is locked in like a metronome','Building base fitness, one stroke at a time',
    'The tortoise is still winning','You are training your body to be a machine',
    'Comfortable discomfort, the best kind','Your heart is learning to be more efficient',
    'This pace is deceptively effective','The benefits of this session will echo for days',
    'Zone 2 work is the quiet revolution','You are building capillaries right now',
    'Steady effort, exponential returns','The erg respects your consistency',
    'This is the base camp of Mount Fitness','Your mitochondria are multiplying (probably)',
    'Long and steady wins the endurance game','Every minute adds to your aerobic capacity',
    'This is how you build a bigger engine','The unglamorous work that makes everything else possible',
    'Your body is becoming more efficient with every stroke','Discipline is doing this when nobody is watching',
    'The pace does not change because you do not need it to','You are rowing your way to a stronger heart',
    'This is the part of training that separates good from great','Embrace the grind, love the grind',
    'Your fat metabolism is working overtime right now','Consistent power, consistent progress',
    'The split time is your north star','This effort will make your sprints faster',
    'Rowing like a river, constant and powerful','Your cardiovascular system is getting an upgrade',
    'One stroke at a time, one minute at a time','The steady state is the state of champions',
    'Your lungs are expanding their capacity','This is how legends build their base',
    'Slow cooking fitness, best results guaranteed','The erg is your meditation cushion today',
    'Hours like these build iron endurance','You are becoming more efficient with every passing minute'
  ],
  countdown:[]
};
const cheerSeen={};
function pickCheer(t){
  const p=CH[t]||[];if(!p.length)return '';
  if(!cheerSeen[t]||cheerSeen[t].length>=p.length)cheerSeen[t]=[];
  const seen=cheerSeen[t];
  const avail=[];for(let i=0;i<p.length;i++){if(!seen.includes(i))avail.push(i)}
  const i=avail[Math.floor(Math.random()*avail.length)];
  seen.push(i);return p[i];
}
export{cheerSeen,pickCheer};
